version: '3.4'

services:
  eureka:
    image: cc.before30.home/grpcex-discovery:latest
    ports:
      - 8761:8761
  server1:
    image: cc.before30.home/grpcex-server:latest
    links:
      - eureka
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
      - grpc.port=6551
    ports:
      - 8081:8080
      - 6551:6551
  server2:
    image: cc.before30.home/grpcex-server:latest
    links:
      - eureka
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
      - grpc.port=6552
    ports:
      - 8082:8080
      - 6552:6552
  server3:
    image: cc.before30.home/grpcex-server:latest
    links:
      - eureka
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
      - grpc.port=6553
    ports:
      - 8083:8080
      - 6553:6553
  server4:
    image: cc.before30.home/grpcex-server:latest
    links:
      - eureka
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
      - grpc.port=6554
    ports:
      - 8084:8080
      - 6554:6554