DROP TABLE IF EXISTS CUSTOMERS;
CREATE TABLE CUSTOMERS(
    CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(150) NOT NULL                  COMMENT '사용자 이름'
);

DROP TABLE IF EXISTS MOVIES;
CREATE TABLE MOVIES(
    MOVIE_ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(150) NOT NULL                 COMMENT '영화 제목',
    RUNNING_TIME INT NOT NULL                   COMMENT '영화 상영 시간',
    PRICE INT NOT NULL                            COMMENT '영화 가격'
);

DROP TABLE IF EXISTS SHOWINGS;
CREATE TABLE SHOWINGS(
    SHOWING_ID INT PRIMARY KEY AUTO_INCREMENT,
    MOVIE_ID INT NULL                           COMMENT '영화 ID',
    SEQUENCE INT NOT NULL                       COMMENT '영화 회차',
    SHOWING_START_TIME DATETIME(6) NOT NULL     COMMENT '영화 시작 시간'
);

DROP TABLE IF EXISTS RESERVATIONS;
CREATE TABLE RESERVATIONS(
    RESERVATION_ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INT NULL                        COMMENT '사용자 ID',
    SHOWING_ID INT NULL                         COMMENT '상영 ID',
    AMOUNT INT NOT NULL                         COMMENT '총 가격',
    AUDIENCE_COUNT INT NOT NULL                 COMMENT '예약 사람 수'
);

--     CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 시간',
--     LAST_MODIFIED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '업데이트 시간'
